utmapp/UTM

ConfigurationViews/VMConfigSystemViewController.m
Managers/UTMQemuSystem.m

* launch qemu with -machine virt
* remove qxl
* fixed dylib filename generation

aarch64 fixes:

---

.gitignore
UTM.xcodeproj/project.pbxproj
UTM.xcodeproj/project.xcworkspace/contents.xcworkspacedata
UTM.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
UTM/AppDelegate.m
UTM/main.m

A somewhat trivial pull request to make working with the project a bit easier as I get acquainted with the system. Finally got it to build…
(FYI: it's `PT_TRACE_ME` on Darwin; that was an oversight on my part when I left that comment)
Update: this also fixes another big annoyance, #32.

Improve usability

---

CocoaSpice/CSMain.m
Configuration/UTMConfiguration.h
Configuration/UTMConfiguration.m
ConfigurationViews/VMConfigExistingViewController.h
ConfigurationViews/VMConfigExistingViewController.m
Managers/UTMLogging.h
Managers/UTMLogging.m
Managers/UTMQemu.m
Managers/UTMVirtualMachine.m
UTM.xcodeproj/project.pbxproj
UTM/Base.lproj/Main.storyboard

This adds a new option to log to file and a way to export the log for debug purposes.
Resolves #99

Redirect stdout/stderr to log file

---

Configuration/UTMConfiguration.h
Configuration/UTMConfiguration.m
ConfigurationViews/VMConfigDriveDetailViewController.h
ConfigurationViews/VMConfigDriveDetailViewController.m
ConfigurationViews/VMConfigDrivesViewController.m
Managers/UTMQemuSystem.m
UTM/Base.lproj/Main.storyboard

Extend support for aarch64 with more configuration options

---

UTM/Base.lproj/Main.storyboard
UTM/zh-Hans.lproj/Main.strings

Sorry for forgetting to relink VMConfigExistingViewController last time...😂

Localizable for zh-Hans and relink the nameFieldChanged event to VMConfigExistingViewController

---

UTM/Base.lproj/Main.storyboard
Views/VMDisplayMetalViewController.m

Improve toolbar contrast and enable pointer highlight effects

---

CocoaSpice/CSDisplayMetal.m
CocoaSpice/CSInput.h
CocoaSpice/CSInput.m
CocoaSpice/CSMain.m
Configuration/UTMConfiguration.h
Configuration/UTMConfiguration.m
ConfigurationViews/VMConfigInputViewController.h
ConfigurationViews/VMConfigInputViewController.m
Managers/UTMQemuManager.h
Managers/UTMQemuManager.m
Managers/UTMQemuSystem.m
Managers/UTMVirtualMachine.h
Managers/UTMVirtualMachine.m
UTM/Base.lproj/Main.storyboard
UTM/Info.plist
UTM/Settings.bundle/Root.plist
Views/VMCursor.m
Views/VMDisplayMetalViewController+Touch.h
Views/VMDisplayMetalViewController+Touch.m
Views/VMDisplayMetalViewController.h
Views/VMDisplayMetalViewController.m

Support touchscreen input

---

UTM.xcodeproj/project.pbxproj
UTM/Base.lproj/Main.storyboard
UTM/zh-Hans.lproj/Main.strings
Views/VMDisplayMetalViewController+Pointer.h
Views/VMDisplayMetalViewController+Pointer.m
Views/VMDisplayMetalViewController.m

This PR fixes #176 and contains parts of #160 
Adds pointer interaction support to:
UI:
- VM List cells
- VM View toolbar buttons
VM:
- Cursor movement
- Auto hiding iPadOS cursor when inside VM display area
Missing:
- Configuration views, any other views not mentioned

Implement iPadOS 13.4 Pointer Interaction for UI and VM

---

CocoaSpice/CSConnection.h
CocoaSpice/CSConnection.m
CocoaSpice/CSConnectionDelegate.h
CocoaSpice/CSSession.h
CocoaSpice/CSSession.m
ConfigurationViews/VMConfigSharingViewController.h
ConfigurationViews/VMConfigSharingViewController.m
Managers/UTMQemuSystem.m
Managers/UTMSpiceIO.m
UTM.xcodeproj/project.pbxproj
UTM/Base.lproj/Main.storyboard

Shared clipboard with guest tools

---

CocoaSpice/CSConnection.m
CocoaSpice/CSConnectionDelegate.h
CocoaSpice/CSSession.h
CocoaSpice/CSSession.m
Configuration/UTMConfiguration+Sharing.h
Configuration/UTMConfiguration+Sharing.m
Configuration/UTMConfiguration.h
Configuration/UTMConfiguration.m
ConfigurationViews/VMConfigSharingViewController.m
Managers/UTMQemuSystem.m
Managers/UTMSpiceIO.m
UTM.xcodeproj/project.pbxproj
UTM/Base.lproj/Main.storyboard
patches/libsoup-2.65.1.patch
patches/phodav-2.2.patch
scripts/build_dependencies.sh
scripts/sources

Shared directory

---

Managers/UTMLocationManager.h
Managers/UTMLocationManager.m
UTM.xcodeproj/project.pbxproj
UTM/Info.plist
UTM/Settings.bundle/Root.plist
Views/UIViewController+Extensions.h
Views/UIViewController+Extensions.m
Views/VMDisplayMetalViewController+Keyboard.m
Views/VMDisplayMetalViewController+Touch.m
Views/VMDisplayMetalViewController.h
Views/VMDisplayMetalViewController.m
Views/VMTerminalViewController.m

Background mode with location services

---

CocoaSpice/CSDisplayMetal.h
CocoaSpice/CSDisplayMetal.m
Configuration/UTMConfiguration+Constants.m
Configuration/UTMConfiguration+Display.h
Configuration/UTMConfiguration+Display.m
Renderer/UTMRenderer.h
Renderer/UTMRenderer.m
Renderer/UTMShaderTypes.h
Renderer/UTMShaders.metal
Views/HTerm/terminal.js
Views/VMDisplayMetalViewController.m
Views/VMTerminalViewController.h
Views/VMTerminalViewController.m

SPICE scaling, auto change resolution & terminal font/cursor settings

---

Configuration/UTMConfiguration+Miscellaneous.h
Configuration/UTMConfiguration+Miscellaneous.m
UTM.xcodeproj/project.pbxproj
UTM/Base.lproj/Main.storyboard
UTM/Settings.bundle/Root.plist
Views/VMCursor.h
Views/VMCursor.m
Views/VMDisplayMetalViewController+Pointer.m
Views/VMDisplayMetalViewController+Touch.h
Views/VMDisplayMetalViewController+Touch.m
Views/VMDisplayMetalViewController.h
Views/VMScroll.h
Views/VMScroll.m

iPadOS 13.4 touchpad gesture handler

---

Configuration/UTMConfiguration+Display.h
Configuration/UTMConfiguration+Display.m
UTM/Base.lproj/Main.storyboard
Views/HTerm/terminal.js
Views/VMDisplayTerminalViewController.h
Views/VMDisplayTerminalViewController.m

Fix up terminal display issues

---

README 日本語.md

readme.Japanese.md

---

README.zh-Hans.md
README.zh-Hant.md
UTM/Settings.bundle/zh-Hans.lproj/Root.strings
UTM/Settings.bundle/zh-Hant.lproj/Root.strings
UTM/zh-Hans.lproj/InfoPlist.strings
UTM/zh-Hans.lproj/Localizable.strings
UTM/zh-Hans.lproj/Main.strings
UTM/zh-Hant.lproj/InfoPlist.strings
UTM/zh-Hant.lproj/Localizable.strings
UTM/zh-Hant.lproj/Main.strings

Optimized the translation of simplified and traditional Chinese characters,  and the Settings are more user-friendly
The traditional Chinese version of README was created
modified some of the explanations in the README and iPhone screenshots so that they can be accessed successfully in China #424

Update zh-Hans & zh-Hant translation

---

Platform/zh-Hans.lproj/Localizable.strings

- fix some bugs.
- add the translation for the new options of the new versions.

localizable: translation for zh-Hans updated.

---

Configuration/UTMConfiguration+Drives.m
Platform/UTMData.swift
Platform/iOS/Legacy/VMConfigDriveDetailViewController.m
Platform/iOS/VMConfigDrivesView.swift
Platform/macOS/VMConfigDrivesView.swift

Fix crash when opening VM configuration #2284

---

Configuration/UTMConfiguration+Constants.h
Configuration/UTMConfiguration+Constants.m
Configuration/UTMConfiguration+ConstantsGenerated.m
Configuration/UTMConfiguration+Defaults.m
Configuration/UTMConfiguration+Display.h
Configuration/UTMConfiguration+Display.m
Managers/UTMQemuSystem.m
Platform/Shared/VMConfigDisplayView.swift
Platform/iOS/Legacy/Base.lproj/Main.storyboard

Make the -device graphics card argument configurable in the display config page 
#303

Graphics card argument configurable

---

Managers/UTMQemuSystem.m

Fix missing comma in network restrict parameter

---

Platform/iOS/Display/VMDisplayMetalViewController+Pointer.h
Platform/iOS/Display/VMDisplayMetalViewController+Pointer.m
Platform/iOS/Display/VMDisplayMetalViewController+Touch.m
Platform/iOS/Display/VMDisplayMetalViewController.h
Platform/iOS/Display/VMDisplayMetalViewController.m

With this api applied, the mouse in virtual machine performs like a real mouse
the mouse cursor will not get out of the screen of virtual machine, or trigger the notification center and multi-task window
https://user-images.githubusercontent.com/9637998/111026862-b5958c80-8427-11eb-9a1e-71ea4ec3eead.mov

iOS: use GCMouse API on iOS 14 and above

---

Platform/Shared/VMPlaceholderView.swift

Update User Guide link on iOS
Add Support link on macOS and FAQ link on iOS
and remove some unnecessary `Spacer()`s
Only thing missing is the localization.

Update Welcome Screen links

---

Platform/iOS/Legacy/zh-Hant.lproj/Main.strings
Platform/iOS/Settings.bundle/zh-Hant.lproj/Root.strings
Platform/iOS/zh-Hant.lproj/InfoPlist.strings
Platform/macOS/zh-Hant.lproj/InfoPlist.strings
Platform/zh-Hant.lproj/InfoPlist.strings
Platform/zh-Hant.lproj/Localizable.strings
QEMUHelper/zh-Hant.lproj/InfoPlist.strings
QEMUHelper/zh-Hant.lproj/Localizable.strings
UTM.xcodeproj/project.pbxproj

I'm a UTM on macOS user, and I'm satisfied with UTM thus I want to contribute to it. I found that the localization of UTM is incomplete and not matched to our zh-Hant user's habit. Thus I complete the localization and reviewed all strings to ensure it matched our habit.

l10n: zh-Hant: reviewed all and localized most strings

---

Managers/UTMQemuSystem.m

Add nodefaults QEMU argument to suppress default devices #2538

---

Platform/iOS/Settings.bundle/zh-Hans.lproj/Root.strings
Platform/iOS/zh-Hans.lproj/InfoPlist.strings
Platform/iOS/zh-Hant.lproj/InfoPlist.strings
Platform/zh-Hans.lproj/InfoPlist.strings
Platform/zh-Hans.lproj/Localizable.strings

Enhance zh-Hans translation, fix app name mistake.

Localize: Enhance zh-Hans translation, fix app name mistake.

---

Platform/iOS/zh-Hant.lproj/InfoPlist.strings
Platform/zh-Hant.lproj/Localizable.strings
UTM.xcodeproj/project.pbxproj
zh-Hant.lproj/QEMULauncher-InfoPlist.strings

With [`Use Compiler to Extract Swift Strings`](http://www.wwdcnotes.com/notes/wwdc21/10220/)

l10n: zh-Hant: update translation

---

Platform/Shared/InListButtonStyle.swift
Platform/Shared/NumberTextField.swift
Platform/Shared/RAMSlider.swift
Platform/Shared/VMWizardDrivesView.swift
Platform/Shared/VMWizardHardwareView.swift
Platform/Shared/VMWizardOSLinuxView.swift
Platform/Shared/VMWizardOSMacView.swift
Platform/Shared/VMWizardOSOtherView.swift
Platform/Shared/VMWizardOSView.swift
Platform/Shared/VMWizardOSWindowsView.swift
Platform/Shared/VMWizardSharingView.swift
Platform/Shared/VMWizardStartView.swift
Platform/Shared/VMWizardState.swift
Platform/Shared/VMWizardSummaryView.swift
Platform/iOS/VMWizardView.swift
Platform/macOS/VMWizardView.swift
UTM.xcodeproj/project.pbxproj

Wizard UI: Better user experience for iOS Users.

---

Platform/zh-Hans.lproj/Localizable.strings
README.zh-Hans.md

- correct some mistakes.
- enhance the translation.

Localize: zh-Hans translation updated.

---

Documentation/TetheredLaunch.zh-HK.md
Documentation/TetheredLaunch.zh-Hant.md

Create the documentation in Traditional Chinese with direct translation from Simplified Chinese.

Create 2 File Documentations

---

Platform/Shared/VMWizardOSMacView.swift

A bit faster than going through the Open dialog

Added support to drag and drop IPSW into wizard

---

.github/ISSUE_TEMPLATE/bug_report_macos.md

Adds detailed steps on how to get the config.plist, as well as general updates to wording.

Update Mac issue template

---

Platform/Shared/ContentView.swift
Platform/UTMData.swift
Platform/iOS/Settings.bundle/Root.plist

Add settings to enable attach and change IP address.
Video demo:
https://user-images.githubusercontent.com/71804605/172005618-4a91b1d7-74e5-4532-876b-f84dc881ac41.mp4

jit: implement JitStreamer attach

---

Platform/es-419.lproj/InfoPlist.strings
Platform/es-419.lproj/Localizable.strings
Platform/es-419.lproj/Localizable.stringsdict
Platform/iOS/Display/es-419.lproj/VMDisplayMetalViewInputAccessory.strings
Platform/iOS/es-419.lproj/InfoPlist.strings
Platform/macOS/Display/es-419.lproj/VMDisplayWindow.strings
Platform/macOS/es-419.lproj/InfoPlist.strings
QEMUHelper/es-419.lproj/InfoPlist.strings
QEMUHelper/es-419.lproj/Localizable.strings
UTM.xcodeproj/project.pbxproj

- Added Spanish (Latin America) or es-419 localization.

Add Spanish (Latin America) localization

---

Platform/Shared/ContentView.swift

Fix: https://discord.com/channels/674683213217792078/674685003988336640/1010076194668027934

jit: use JitStreamer if enabled even when AltJit available

---

Platform/macOS/VMConfigAppleDisplayView.swift

Add 5K ultrawide resolution for Apple VMs

---

Platform/fr.lproj/Localizable.strings

Fix typos and enhance readability.

Improve french localization

---

Platform/es-419.lproj/Localizable.strings
Platform/iOS/Display/es-419.lproj/VMDisplayMetalViewInputAccessory.strings
Platform/iOS/Settings.bundle/es-419.lproj/Root.strings
Platform/iOS/es-419.lproj/InfoPlist.strings
Platform/macOS/Display/es-419.lproj/VMDisplayWindow.strings
Platform/macOS/es-419.lproj/InfoPlist.strings
QEMUHelper/es-419.lproj/InfoPlist.strings
QEMUHelper/es-419.lproj/Localizable.strings
UTM.xcodeproj/project.pbxproj
es-419.lproj/QEMULauncher-InfoPlist.strings

Update Spanish (Latin America) or es-419 localization to latest UTM updates.

Update Spanish (Latin America) localization

---

Platform/macOS/VMConfigAppleDisplayView.swift

added support for 3440x1440 widescreen, aspect 21:9 displays

---

Platform/Shared/DetailedSection.swift
Platform/Shared/VMConfigDisplayConsoleView.swift
Platform/Shared/VMConfigInfoView.swift
Platform/Shared/VMConfigInputView.swift
Platform/Shared/VMConfigQEMUView.swift
Platform/Shared/VMConfigSerialView.swift
Platform/Shared/VMConfigSharingView.swift
Platform/Shared/VMConfigSystemView.swift
Platform/macOS/VMAppleSettingsView.swift
Platform/macOS/VMQEMUSettingsView.swift
Platform/macOS/VMSettingsView.swift

Some SwiftUI previews regarding to VM settings were not rendering properly or not displaying at all. This PR fixes some of these issues.

Fix some SwiftUI previews

---

Platform/iOS/Display/ja.lproj/VMDisplayMetalViewInputAccessory.strings
Platform/iOS/Settings.bundle/ja.lproj/Root.strings
Platform/iOS/ja.lproj/InfoPlist.strings
Platform/ja.lproj/Localizable.strings
Platform/macOS/Display/ja.lproj/VMDisplayWindow.strings
Platform/macOS/ja.lproj/InfoPlist.strings
QEMUHelper/ja.lproj/InfoPlist.strings
QEMUHelper/ja.lproj/Localizable.strings
UTM.xcodeproj/project.pbxproj

Slightly improved Japanese translation.

Improve Japanese translation

---

Platform/de.lproj/Localizable.strings

Improved and fixed German translation.

Updated German translation

---

Platform/pl.lproj/Localizable.strings

Fixed gramatical errors and improved the wording of some translations. Fixed some strings that were translated to French instead of Polish. Added translations for serial interfaces and devices. Would appreciate if someone looked at lines containing "serial" and "%lld" to maybe make the translation fit better.

Update Polish translation

---

Platform/iOS/Display/zh-Hant.lproj/VMDisplayMetalViewInputAccessory.strings
Platform/macOS/Display/zh-Hant.lproj/VMDisplayWindow.strings
Platform/macOS/zh-Hant.lproj/InfoPlist.strings
Platform/zh-Hant.lproj/Localizable.strings
Platform/zh-Hant.lproj/Localizable.stringsdict
QEMUHelper/zh-Hant.lproj/Localizable.strings
UTM.xcodeproj/project.pbxproj
zh-Hant.lproj/QEMULauncher-InfoPlist.strings

Extracted with Swift Compiler. Total 814 strings (100%). Based on [v4.3.5](https://github.com/utmapp/UTM/tree/v4.3.5)

l10n: zh-TW: update translation

---

README.es.md

* fixes in lines 09, 25, 
* fixed typo in line 35,
* link is not working in line 71

Minor proposals on README.md 

---

README.ko.md

at first, I should thank you. I have passed some task in university using this.
I think many students who use macOS in Korea graduated through this. who know? some of them will contribute to this, maybe. I made a first step for them.

docs: added README for korean

---

Platform/iOS/it.lproj/InfoPlist.strings
Platform/it.lproj/Localizable.strings
Platform/it.lproj/Localizable.stringsdict
Platform/macOS/Display/it.lproj/VMDisplayWindow.strings
Platform/macOS/it.lproj/InfoPlist.strings
QEMUHelper/it.lproj/InfoPlist.strings
QEMUHelper/it.lproj/Localizable.strings
UTM.xcodeproj/project.pbxproj

Adding Italian Language support.

Add Italian localization

---

Platform/iOS/Display/zh-Hans.lproj/VMDisplayMetalViewInputAccessory.strings
Platform/iOS/Settings.bundle/zh-HK.lproj/Root.strings
Platform/iOS/Settings.bundle/zh-Hans.lproj/Root.strings
Platform/iOS/zh-HK.lproj/InfoPlist.strings
Platform/iOS/zh-Hans.lproj/InfoPlist.strings
Platform/macOS/Display/zh-HK.lproj/VMDisplayWindow.strings
Platform/zh-HK.lproj/Localizable.strings
Platform/zh-Hans.lproj/Localizable.strings
README.zh-HK.md

p.s. Some strings cannot be extracted by Xcode while using the "Exporting Localizations" feature. I have appended the missing strings at the end of each `Localizable.strings` file.

Add more translations for Simplified Chinese and Traditional Chinese (Hong Kong)

---

Platform/it.lproj/Localizable.strings

This PR adds missing strings previously missing and corrects some typos of the Italian Localization.
Mostly adding help popups strings and harmonizing the language used by the translation across the different options.

Improved Italian Localization

---

Documentation/MacDevelopment.md

- Fixed macOS scheme for the example to build from the command line
- Added details for packaging to make it clearer

Updated documentation

---

Platform/macOS/Display/Base.lproj/VMDisplayWindow.xib

Partial fix for https://github.com/utmapp/UTM/issues/5535
Set VM Window collection behavior to FullScreenPrimary. See my comment [here](https://github.com/utmapp/UTM/issues/5535#issuecomment-2053012781).

Partial fix for the #5535 – The issue with full screen not working when dock icon is hidden

---

Platform/iOS/UTMRemoteConnectView.swift
README.md

This is a fix for the case where the crash occurs when iOS 14 device attempts to connect to a UTM Server.
https://github.com/tearsinthegame/UTMRemote-iOS14
The related issue:
https://github.com/utmapp/UTM/issues/6970

Fix for crash while connecting in UTM Remote for iOS 14

---

Platform/fr.lproj/Localizable.strings

Just a translation fix i've seen when we start virtual machine!

Update French Localizable.strings
