utmapp/UTM

- UTM/Base.lproj/Main.storyboard
Fixed issue causing overlap of power and zoom buttons in VMDisplayMetalViewController's toolbar on devices with regular width and compact height (Plus/Max sized iPhones in landscape mode). Also I've embedded these buttons into UIStackView so it's easier to manage them. And finally equalized icon sizes by setting appropriate image insets.
Edit:
Fixes #35
> Fixed toolbar button overlap on Plus/Max iPhones

- .gitignore
- Configuration/UTMConfiguration.h
- Configuration/UTMConfiguration.m
- ConfigurationViews/VMConfigSystemArgumentsViewController.h
- ConfigurationViews/VMConfigSystemArgumentsViewController.m
- ConfigurationViews/VMConfigSystemViewController.h
- ConfigurationViews/VMConfigSystemViewController.m
- Managers/UTMQemuSystem.m
- UTM.xcodeproj/project.pbxproj
- UTM/Base.lproj/Main.storyboard
This partially completes #93. It provides an additional table view separating boot arguments, and has a working method to split the list argument into valid, passable arguments.
Some UX is rather janky in regards to removing inputted text from the UI, so I am submitting this as-is via draft. It additionally does not display flags visually anywhere as the issue calls for.
> Implement argument list view

- Configuration/UTMViewState.h
- Configuration/UTMViewState.m
- Managers/UTMVirtualMachine.m
- Managers/UTMVirtualMachineDelegate.h
- UTM.xcodeproj/project.pbxproj
- Views/VMDisplayMetalViewController.m
- Views/VMListViewController.m
This implements a way to save the current view state for the VM. This includes the scaling, and origin X, Y positions as well as the visibility of the toolbar and keyboard.
Closes #102
> Save view state

- Platform/UTMData.swift
`URL.startAccessingSecurityScopedResource()` is required to access a file outside its sandbox. I added `URL.startAccessingSecurityScopedResource()` and `URL.stopAccessingSecurityScopedResource()` so that UTM can import a disk image. See #490.
Fixes #490
> Fix the error when importing drive

- Platform/Shared/VMToolbarModifier.swift
Currently, the bottom bar of `VMDetailsView` is always shown even if there are no buttons. So, I fixed it.
Then:
Now:
| When `horizontalSizeClass` is `.regular` | When `horizontalSizeClass` isn't `.compact` |
|:--:|:--:|
| ![IMG_0287](https://user-images.githubusercontent.com/601636/95859664-ee0e3d00-0d99-11eb-9a1d-6d1dac33e36e.png) | ![IMG_0288](https://user-images.githubusercontent.com/601636/95859777-139b4680-0d9a-11eb-80bf-500758b32c7f.jpeg) |
> Hide the bottom bar of VMDetailsView when it is not needed

- Managers/UTMVirtualMachine+Drives.m
- Platform/Shared/VMDetailsView.swift
- Platform/Shared/VMRemovableDrivesView.swift
The removable drives list in the VM details isn't very nice to look at currently. This PR includes some of the UI changes from my previous PR #531, and includes a fix for incorrect `UTMDrive.state`.
> Improve removable drives state and UI

- Platform/UTMApp.swift
On macOS, user is able to adjust sidebar width by dragging the separator. If the user drag it to near 0 width, it's impossible to get the sidebar back again. Adding SidebarCommands would have a command in View menu for user to toggle sidebar, as well as a key shortcut for doing so.
> Add SidebarCommands to be able to bring Sidebar back.

- .gitignore
- Managers/UTMQemuSystem.m
Currently UTM adds a USB 2.0 controller for non-virt systems. This causes issues with old Windows guests like 98. So I changed it to add a USB 1.1 controller if the system is `pc`. 
I also added `.DS_Store` files to .gitignore.
> Use USB 1.1 controller for pc systems

- Managers/UTMQemuSystem.m
~~Fixes~~ Partially fixes #3194 (Windows 11 installer causes QEMU EHCI reset, aborting install)
The result of this PR is that for `aarch64` guest, the USB CD drive is connected to the XHCI bus:
This has the nice side effect of increasing the speed of the USB drive.
Edit: added "partially" above to reflect my findings while testing. See [my comment](https://github.com/utmapp/UTM/issues/3194#issuecomment-953314235) for details.
> Set USB-XHCI bus for USB storage when using aarch64 system architecture

- Platform/Shared/UTMImportFromWebTask.swift
- Platform/UTMData.swift
- README.md
- UTM.xcodeproj/project.pbxproj
A file path confusion existed where the downloaded ZIP was extracted to the UTM
Documents directory instead of the temporary folder (I believe this change may have been caused by an update of the ZIP library in use). As a result, UTM failed to import the downloaded file because a folder with the same name already existed (as seen in the console log).
This is fixed by manually specifying the path for the unzip call.
> Fix downloadVM URL action failing to import downloaded file

- AppleVirtualization/UTMAppleConfiguration.swift
I've tried to create a new macOS Monterey VM on a M1 Mac using [v3.0.0 (Beta)](https://github.com/utmapp/UTM/releases/tag/v3.0.0)
It fails with:
> Invalid virtual machine configuration. “auxiliaryStorage” is nil.
As far as I can tell, `apple.validate()` is the call that shows the message.
`auxiliaryStorage` is initialized later in the scope by `saveBootloader()`, but does not get called cause an error is thrown.
I've updated the code so that `apple.validate()` is called *after* `saveBootloader()`.
> Fixed: "auxiliaryStorage is nil" when creating macOS VM on M1 Mac

- Platform/iOS/iOS.entitlements
- scripts/package.sh
As described [here](https://developer.apple.com/forums/thread/685084?answerId=695278022#695278022), you need two entitlements in order to use more than 5 GB of memory on iOS and iPadOS.
`com.apple.developer.kernel.increased-memory-limit` already has been added to [iOS.entitlements](https://github.com/utmapp/UTM/blob/6524c733d36f183c5b393b54e91f7f0cd2ae7ad7/Platform/iOS/iOS.entitlements#L5), but it's insufficient.
The results of my experiments in my app showed that `com.apple.developer.kernel.increased-memory-limit` certainly increased the return value of `os_proc_available_memory`, it was about 12 GB on the iPad Pro that has 16GB of memory, but the actual limit of memory that can be allocated was only about 5 GB. So I also added the `com.apple.developer.kernel.extended-virtual-addressing` …
> iOS: Make it possible to allocate more than about 5 GB of memory

- Managers/UTMQemuSystem.m
https://wiki.qemu.org/Features/VirtIORNG#Invocation
@conath could you help to test that this doesn't break Windows etc. VMs? You can just add `-device virtio-rng-pci` to the QEMU arguments.
**Edit:**
It seems according to [this](https://www.redhat.com/en/blog/red-hat-enterprise-linux-virtual-machines-access-random-numbers-made-easy), virtio RNG should work on Windows guests too?
> Add virtio-rng-pci device to qemu commandline

- Managers/UTMQemuSystem.m
Fixed by checking if the drive interface is "floppy"; if so the media type is set correctly to "disk" instead of "cdrom".
> Fix #3333 floppy drive is read only

- Configuration/UTMQemuConfiguration+Drives.m
QEMU drive ids must start with a letter.
However if an image files was manually placed in the VM images folder,
this code path is triggered and a UUID set for the id.
This causes ids starting with numbers to be set sometimes.
This commit changes the name for these drives to use sequential driveX numbering instead of UUID. Fixes #3388 
Tested successfully on macOS 12.1:
1. Place an image file in the Images folder of an existing UTM VM
2. Opening VM config
3. Click Drives tab
4. Change the new drive at the bottom of the list to type "disk image"
5. Click Save
Start VM → no error
Open Config QEMU tab → see drive id "driveX" instead of UUID.
> Fix #3388 invalid drive id for manually placed files

- Configuration/UTMQemuConfiguration+Defaults.m
Closes #3371
Nearest Neighbor offers better contrast and increases sharpness for upscaling;
the reverse is true for downscaling so it is not changed.
> Change default display upscaling mode to Nearest Neighbor

- Platform/Shared/VMConfigQEMUView.swift
- Platform/Shared/VMContextMenuModifier.swift
- Platform/Shared/VMShareFileModifier.swift
- Platform/Shared/VMToolbarModifier.swift
- Platform/macOS/SavePanel.swift
> sharefilemodifier: take ShareItem as input, not function

- Platform/macOS/Display/VMDisplayMetalWindowController.swift
The scroll amount variable was being properly inverted, but it wasn't
being used in the function call. Also changed to use ternary operator
and no `var`.
Fixes #3497
I checked, and this code problem isn't in the iOS code.
> display(macOS): fix invert mouse scroll doing nothing

- Configuration/UTMAppleConfiguration.swift
I have tested that this change is backward and forward compatible, meaning that I can save an xml config, and open it with UTM 3.0.3 (Beta) which expects a binary config (and if saving changes with 3.0.3 it will re-write it as binary), and I can also open a binary config with this code and when saving it will re-write it as xml.
> config(apple): save config.plist as human-readable xml

- Configuration/UTMAppleConfiguration.swift
- Configuration/UTMConfigurable.h
- Configuration/UTMQemuConfiguration+Constants.h
- Configuration/UTMQemuConfiguration+Constants.m
- Configuration/UTMQemuConfiguration+Display.h
- Configuration/UTMQemuConfiguration+Display.m
- Platform/Shared/HTerm/terminal.js
- Platform/Shared/VMConfigDisplayConsoleView.swift
- Platform/UTMExtensions.swift
- Platform/iOS/Display/VMDisplayTerminalViewController.m
- Platform/macOS/Display/VMDisplayAppleWindowController.swift
- Platform/macOS/Display/VMDisplayTerminalWindowController.swift
- Platform/macOS/VMAppleSettingsView.swift
See the individual commit messages for more details, but here's an overview:
- Add `consoleTextColor` and `consoleBackgroundColor` values to `UTMConfigurable`, and implement the setters/getters in `UTMConfiguration+Display` that use a keyed archiver to convert the `NSColor` into `NSData` that can be stored in `config.plist`. (This is needed because if I just save the hex values, there is a lot of drift in the color picker because of the loss in converting to/from a hex string, and it's done on each color value change)
- Add `ColorPicker`s to the display console configuration.
- Add and call a Javascript method that sets the color values in the hterm prefs.
- Save the color settings as hex strings when using the apple virtualization backend. This is fine because the conversion is only done …
> Add support for changing console colors, properly load available font list on macOS

- Platform/Shared/VMWizardOSWindowsView.swift
- Platform/iOS/Settings.bundle/zh-Hans.lproj/Root.strings
- Platform/zh-Hans.lproj/Localizable.strings
It seems markdown text in TextView without using AttributedString(markdown:) works fine in iOS 15 and macOS 12. The link is still clickable. I changed this for localization.
> Localization for zh-Hans updated.

- Platform/iOS/Display/VMDisplayMetalViewController+Touch.m
- Platform/iOS/Display/VMDisplayMetalViewController.h
When a VM is running with a cursor in server mode, it is possible via `gesturePan:` to drag the Apple Pencil across the screen which moves the mouse cursor in the VM. As a result, it seemed intuitive that tapping the pencil would generate a click event.
Since the logic that currently handles this in `touchesBegan:` can only be reached while the input mode is non-legacy and the cursor is in client mode, and `gestureTap:`'s recogniser is filtered to only accept direct input, touching the pencil on the screen in other conditions goes unhandled, meanwhile `gesturePan:`'s recogniser does not filter the input source so cursor movements still function.
Here, another gesture recogniser is added exclusively to handle pencil taps on the screen, so as to enable the expected click behaviour and to …
> Apple Pencil tap while using server cursor mode

- README.md
This commit achieves the following:
- I will not be doing this for the simplified or traditional Chinese READMEs as the author of those appears to be using their own hosting provider for the images, so they can grab the new image and translate the alt text to the respective Chinese if they wish.
On a desktop browser:
----
On a mobile phone:
> Add image of UTM running on macOS to en-US README

- Platform/Shared/UTMDownloadIPSWTask.swift
Fix for #4141 
Just checking if the folder exists and create it if not. The problem with #4141 was a missing "Caches" folder.
> When downloading macOS IPSW: Check if "Caches" folder exists and create it if not

- Configuration/UTMQemuConfiguration+Arguments.swift
This change allows directory sharing using virtio/9p without requiring other sharing options to be enabled.
Updates #2184
> vm(qemu): allow virtio/9p without other sharing options

- Platform/de.lproj/Localizable.strings
- Platform/es-419.lproj/Localizable.strings
- Platform/fr.lproj/Localizable.strings
- Platform/ja.lproj/Localizable.strings
- Platform/macOS/VMConfigAppleSharingView.swift
- Per ktprograms in Discord, permissions to access paths are now present in 4.x and this warning is no longer needed as files are no longer deleted
> Removed incorrect "Shared directories" warning message

- Documentation/MacDevelopment.md
Quick fix for formatting and making the commands directly copyable.
Fixes #4606
> Fixed MacDevelopment.md shell commands formatting.

- Platform/UTMData.swift
Use `copyfile(3)` with `COPYFILE_DATA_SPARSE` flag which attempts to preserve sparseness when copying across different volumes, which `FileManger.copyItem(at:, to:)` doesn't. Cloning behaviour from `FileManger.copyItem(at:, to:)` is preserved with the `COPYFILE_CLONE` flag.
@osy I don't have the hardware to test this on iOS/iPadOS, could you please help me to test it? In theory it should Just Work.
Also, please see my message in the DIscord's #general about whether the sparse copy is needed for importing drives.
~~Also, I'm not sure if the alloc and free of `copyfile_state_t` is necessary, some code has it and some don't. It seems to work the same either way.~~ Edit: According to the manpage, it can be `NULL`/`nil`:
If the state parameter is the return value from copyfile_state_alloc(), …
> data: support sparse copy across volumes

- Platform/pl.lproj/Localizable.strings
Fixed overlooked typo to avoid confusion with memory size provided by user.
> Polish localization: fix typo

- Platform/macOS/Display/VMDisplayQemuMetalWindowController.swift
- Platform/macOS/KeyCodeMap.swift
Fixed an issue where Japanese-specific keys `英数 (Eisu)` / `かな (Kana)` do not work.
These keys are mapped as fallback to `無変換 (Muhenkan)` / `変換 (Henkan)`.
> Fix Japanese-specific key issues

- Platform/fr.lproj/Localizable.strings
This pull request fixes a few problems with the fr locale:
1. Removed full-width CJK parenthesis `（` and `）` that should not be used in French.
2. Replaced with curly quotes that match the style of native macOS texts.
> Fix fr locale

- README.ru.md
* Added a (mostly literal) Russian translation of `README`
* Reordered some paragraphs (e.g. the icons attribution appears after components’ licensing description, not in the middle of it)
* Moved existing links to in-place to prevent unused references (such as `[2]` in [the English version](https://github.com/utmapp/UTM/blob/main/README.md?plain=1)) in the future
* Added more links to documentation, explanations, etc.
> `README` in Russian

- Platform/zh-Hant.lproj/Localizable.strings
- QEMUHelper/zh-Hant.lproj/Localizable.strings
- README.zh-Hant.md
Fix those using Simplified Chinese terms in Traditional Chinese characters but not properly translated.
> Fix/Update zh-Hant localization

- Platform/iOS/zh-HK.lproj/InfoPlist.strings
- Platform/iOS/zh-Hans.lproj/InfoPlist.strings
**Describe the issue**
The "CFBundleName" is configured as "UTM SE," causing the app name to consistently appear as "UTM SE"
**Affected languages**
Chinese Simplified, Chinese Traditional
The builds of UTM or UTM-HV are both displayed as "UTM SE"
> [Localizable] The App name is translated to "UTM SE" by mistake

- Platform/Shared/VMRemovableDrivesView.swift
- Services/UTMQemuVirtualMachine.swift
Adding drag and drop feature for VMRemovableDrivesView using SwiftUI `onDrop` functionality.
In addition to the main purpose, I have also removed unused extra argument `url` from `changeMedium` function in `UTMQemuVirtualMachine.swift` which I noticed during code browsing.
fixes: https://github.com/utmapp/UTM/issues/3312
> Adding drag and drop feature for VMRemovableDrivesView

- Platform/macOS/Display/VMDisplayQemuMetalWindowController.swift
Make the window auto-capture the mouse again in full screen when it regains focus (for instance after swiping back to the UTM app).
fixes #6242
> Re-grab input when automatic capture is enabled

- Platform/Shared/VMConfigInfoView.swift
Solved "Add a tooltip when selecting an OS icon for the selected VM?" #5937
macOS
Removed extra icon picker pop over for iOS / iPadOS 
iPadOS
iOS
> Issue #5937 - improved VM icon selector UX

- Platform/Shared/RAMSlider.swift
- Platform/Shared/SizeTextField.swift
- Platform/Shared/VMConfigSystemView.swift
- Platform/Shared/VMWizardDrivesView.swift
- Platform/de.lproj/Localizable.strings
- Platform/es-419.lproj/Localizable.strings
- Platform/fi.lproj/Localizable.strings
- Platform/fr.lproj/Localizable.strings
- Platform/it.lproj/Localizable.strings
- Platform/ja.lproj/Localizable.strings
- Platform/ko.lproj/Localizable.strings
- Platform/pl.lproj/Localizable.strings
- Platform/ru.lproj/Localizable.strings
- Platform/zh-HK.lproj/Localizable.strings
- Platform/zh-Hans.lproj/Localizable.strings
- Platform/zh-Hant.lproj/Localizable.strings
This shouldn't normally bother anyone but I've ran to a kernel panic on a niche OS and found out binary units are being used instead of decimal units displayed in disk settings. This PR also fixes this misuse in other areas where binary units are used (JIT Cache and Memory). I also replaced Finnish abbreviation with global one since nobody uses that way.
> Replace GB/MB with GiB/MiB since binary units are actually being used

- Platform/fr.lproj/Localizable.strings
There is a typo in the French translation of "New Drive" as the current word does not exist in this language. This PR fixes it.
> Fix typo in French translation of "New Drive"

- Scripting/UTM.sdef
- Scripting/UTMScripting.swift
- Scripting/UTMScriptingExportCommand.swift
- Scripting/UTMScriptingVirtualMachineImpl.swift
- UTM.xcodeproj/project.pbxproj
- utmctl/UTMCtl.swift
- utmctl/utmctl-unsigned.entitlements
Fixes #6553 
* Exposed VM export via Apple Scripting and CLI
* Turned on sandbox for unsigned utmctl binary to be consistent with unsigned UTM. So we can test the same data across unsigned products.
Example: 
Usage in AppleScript
```applescript
tell application "/Users/***/UTM.app"
set vm to virtual machine named "ubuntu"
set output to POSIX file "/Users/***/ubuntuExport.utm"
export vm to output
end tell
```
Usage in cli (path must be writable by utmctl)
```bash
utmctl export ubuntu --path /Users/***/ubuntuExport.utm
```
> scripting: add export command

- Scripting/UTM.sdef
- Scripting/UTMScriptingConfigImpl.swift
Fixes #6661 
read and update qemu additional argument of vm config
Usage:
```applescript
tell application "/Users/xxx/UTM.app"
set vm to virtual machine named "VM"
set config to configuration of VM
-- read  qemu additional arguments 
set qemuAddArgs to qemu additional arguments of config
-- add
set newArg to {{argument string:"-vnc 127.0.0.1:1"}}
set qemuAddArgs to qemuAddArgs & newArg
-- update 
set qemu additional arguments of config to qemuAddArgs
update configuration of vm with config
end tell
```
This will enable to launch VMs with custom qemu args via APIs
Related #5211
> scripting: add qemu additional arguments

- Platform/iOS/Donation.storekit
- Platform/iOS/zh-HK.lproj/Info-Remote-InfoPlist.strings
- Platform/iOS/zh-HK.lproj/InfoPlist.strings
- Platform/iOS/zh-Hans.lproj/Info-Remote-InfoPlist.strings
- Platform/iOS/zh-Hans.lproj/InfoPlist.strings
- Platform/zh-HK.lproj/Localizable.strings
- Platform/zh-Hans.lproj/Localizable.strings
- UTM.xcodeproj/project.pbxproj
p.s. I've also added simplified and traditional Chinese translations for in-app purchase (donation) items in `Platform/iOS/Donation.storekit`.
Sorry for not providing a zh-HK variant for that, because Apple doesn't offer the "Chinese (Hong Kong)" option in Xcode (see the screenshot below).
> Update zh-Hans & zh-HK translations

- Scripting/UTM.sdef
- Scripting/UTMScriptingConfigImpl.swift
- Scripting/UTMScriptingRegistryEntryImpl.swift
- Scripting/UTMScriptingVirtualMachineImpl.swift
- Services/UTMQemuVirtualMachine.swift
- Services/UTMRegistryEntry.swift
- UTM.xcodeproj/project.pbxproj
Fixes #6899
The registry suite is used to read and update vm registry.
All configs saved to disk is exposed by Configuration suite, similarly those that are not saved to disk are stored in RegistryEntry of a VM, they will now be exposed by Registry suite.
Users will now be able to give UTM→QEMU access to their custom path by updating registry, which can then be used in qemu additional args.
Added
- UTMScriptingRegistryEntryImpl will control what will be exposed from RegistryEntry to scripting bridge, currently only shared directory is exposed in the form of [URL].
Since we have a separate suite for handling registry , this suite can grow on what will be exposed. Eg: externalDrives  (Not everything in RegistryEntry is suitable to be exposed)
- Added file urls to qemu addtional args, QEMU …
> scripting : add vm registry suite

- Scripting/UTM.sdef
- Scripting/UTMScripting.swift
- Scripting/UTMScriptingConfigImpl.swift
Fixes #6660 
* qemu display
- All fields , except vga ram is exposed 
* apple display
- only dynamic resolution property is exposed.
- From GUI , the height, width and pixel of resolution is in pre-defined ratio and hence not exposed.
Both displays will have ids, which can be used to track and detach the displays.
add_qemu_display.applescript
```applescript
on run argv
set vmName to item 1 of argv
tell application "UTM"
set vm to virtual machine named vmName
set config to configuration of vm
set currentDisplay to displays of config
set newDisplay to ¬
{ ¬
hardware: "virtio-gpu-pci", ¬
dynamic resolution: false, ¬
native resolution: true, ¬
upscaling filter: "QsLi", ¬
downscaling filter: "QsNe" ¬
}
set end of currentDisplay to newDisplay
set displays of config to currentDisplay
update …
```
> scripting: expose display config

- Configuration/UTMConfigurationHostNetwork.swift
- Configuration/UTMQemuConfiguration+Arguments.swift
- Configuration/UTMQemuConfigurationNetwork.swift
- Platform/Shared/VMConfigNetworkView.swift
- Platform/macOS/SettingsView.swift
- UTM.xcodeproj/project.pbxproj
This adds support for connecting QEMU VMs to specific host networks using the `net-uuid` option (described [here](https://www.qemu.org/docs/master/interop/qemu-qmp-ref.html#qapidoc-1445)). This can be extremely useful when connecting multiple VMs together, or for connecting VMs across virtualisation applications (VMware Fusion/Parallels). Unfortunately, I didn't find such option for the Apple virtualisation APIs, so it's only supported for QEMU VMs. #4190 essentially accomplished this by manually editing the QEMU arguments.
Note that using a custom network UUID will disable the DHCP that macOS vmnet would otherwise provide. As of right now, the user is responsible for providing their own DHCP on the network. E.g. by running a VM that provides it, or running a VM in e.g. VMware on the same …
> Initial support for external/multiple networks in vmnet host mode

- Platform/macOS/SettingsView.swift
This pull request adds a workaround to this issue by increasing the vertical window size of the settings screen as a whole by 20 pixels.
Here's a screenshot of the previous setting screen with the inputs tab (where some settings got cut out):
And here's the screenshot with the fix:
> macOS: fix issue where the Settings window (via cmd+,) was scaled to be too short when showing the inputs tab

- Scripting/UTM.sdef
- Scripting/UTMScripting.swift
- Scripting/UTMScriptingVirtualMachineImpl.swift
- utmctl/UTMCtl.swift
Add an optional flag to `utmctl start` to boot a VM into recovery mode, eg `utmctl start --recovery macOS`.
- defaults to False
- verifies the VM supports recovery mode
> utmctl: support booting into recovery mode

- Platform/Shared/VMConfigNetworkView.swift
- Platform/macOS/VMConfigAppleNetworkingView.swift
This adds the localized interface name in bridge network configuration, which makes them a little easier to recognize.
QEMU configuration:
Apple configuration:
> Show localized bridge network name when available

- Configuration/UTMQemuConfiguration+Arguments.swift
- Intents/UTMInputIntent.swift
- Platform/Shared/VMWizardHardwareView.swift
Fixes typos in comments across multiple Swift files.
- Corrected minor spelling errors (e.g. "Disply" → "Display", "sever" → "server", “sequnce” → “sequence”)
These fixes improve readability and maintain professionalism in the codebase.
---
Let me know if you'd prefer a more granular set of commits or changes.
> chore: fix grammar in code comments

- Platform/ru.lproj/Localizable.strings
It should say "Запущена" in this case - since "Запущенно" doesn't fit this context and we're talking about VM (машина is a feminine noun, and "Запущено" is for masculine nouns).
> Fix "Started" in ru.lproj
